#!/bin/bash -e

echo "Updating"
sudo pacman -Syu --noconfirm

echo "Looking for orphans"
orphans=$(pacman -Qdtq || true)
if [[ -n "$orphans" ]]; then
    echo "Removing orphaned packages"
    sudo pacman -Rns $orphans --noconfirm
else
    echo "No orphans"
fi

echo "Cleaning cache"
yes | sudo pacman -Sc             

echo "Done"
