#!/bin/bash
set -e

echo "Updating system"
sudo pacman -Syu --noconfirm

echo "Checking for orphaned packages"
orphans=$(pacman -Qdtq || true)
if [[ -n "$orphans" ]]; then
    echo "Removing orphaned packages"
    sudo pacman -Rns $orphans --noconfirm
else
    echo "No orphaned packages found."
fi

echo "Cleaning package cache"
yes | sudo pacman -Sc             
#Its either yes or --noncomfirm, depends on pacman version or something i think

echo "Maintenance complete"
